### PR TITLE
better stiched overview image

### PR DESCRIPTION
**Pull request by martinschorb**
request from Giulia. 

This will make a nicer figure.

### CODE REVIEW

**Comment by martinschorb** [comment]
@constantinpape I still have no write access to the bucket, so if you could please upload that zarr? Thx!

**Comment by constantinpape** [comment]
Cool!

> so if you could please upload that zarr

Sure, can you point me to where it is?

**Comment by martinschorb** [comment]
should be in your source folder...
https://github.com/mobie/mobie-utils-python/issues/51#issuecomment-1091386762

**Comment by martinschorb** [comment]
and I haven't updated the remote source yet, either.

**Comment by martinschorb** [comment]
I uploaded the image data to S3. 
Still, the project crashes when loading. I cannot validate my local checkout, because I don't have the image data locally. Could you have a look what is wrong here?

**Comment by constantinpape** [comment]
I will check it out after Easter.

**Comment by martinschorb** [comment]
Turns out I was just to impatient and the S3 was not completely done with the import copy task.

**Pull request merged**
